<?php declare(strict_types = 1);

/** @var array $data */

$helper = $data['helper'];
$report = $data['report'];
$filter = $data['filter'];
$time_from = (int) $data['time_from'];
$time_to = (int) $data['time_to'];
$metric_label = $helper->getMetricLabel((string) $filter['metric']);
$period_label = $helper->formatPeriodLabel($time_from, $time_to);
$esc = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');

$base_query = [
    'filter_mode' => $filter['mode'],
    'filter_month' => $filter['month'],
    'filter_date_from' => $filter['date_from'],
    'filter_date_to' => $filter['date_to'],
    'filter_days_back' => $filter['days_back'],
    'filter_source' => $filter['source'],
    'filter_metric' => $filter['metric'],
    'filter_top' => $filter['top'],
    'filter_object_search' => $filter['object_search'],
    'filter_repo_search' => $filter['repo_search'],
    'filter_hostids' => $filter['hostids']
];

$download_url = static function(string $format) use ($base_query): string {
    $query = array_merge(['action' => 'veeambackup.report.download', 'format' => $format], $base_query);

    return 'zabbix.php?'.http_build_query($query);
};

ob_start();
?>
<div class="veeamreport">
    <div class="veeamreport-section">
        <h1 class="veeamreport-page-title"><?php echo $esc(_('Veeam Backup Report')); ?></h1>
        <p class="veeamreport-section-subtitle">
            <?php echo $esc(_('Report data is read from Zabbix history/trends generated by the Veeam Backup and Replication by HTTP v13 template.')); ?>
        </p>
    </div>

    <div class="veeamreport-info-bar">
        <span class="veeamreport-info-label"><?php echo $esc(_('Period')); ?>:</span>
        <?php echo $esc($period_label); ?>
        <span class="veeamreport-sep">•</span>
        <span class="veeamreport-info-label"><?php echo $esc(_('Metric')); ?>:</span>
        <?php echo $esc($metric_label); ?>
        <span class="veeamreport-sep">•</span>
        <span class="veeamreport-info-label"><?php echo $esc(_('Source')); ?>:</span>
        <?php echo $esc(ucfirst((string) $report['source_used'])); ?>
    </div>

    <?php foreach (($report['warnings'] ?? []) as $warning): ?>
        <div class="veeamreport-alert veeamreport-alert--warning">
            <?php echo $esc($warning); ?>
        </div>
    <?php endforeach; ?>

    <form method="get" action="zabbix.php" class="veeamreport-filter-form">
        <input type="hidden" name="action" value="veeambackup.report.view">

        <div class="veeamreport-filter-grid">
            <div class="veeamreport-field">
                <label for="filter_mode"><?php echo $esc(_('Period mode')); ?></label>
                <select id="filter_mode" name="filter_mode">
                    <option value="prev_month"<?php echo $filter['mode'] === 'prev_month' ? ' selected' : ''; ?>><?php echo $esc(_('Previous month')); ?></option>
                    <option value="specific_month"<?php echo $filter['mode'] === 'specific_month' ? ' selected' : ''; ?>><?php echo $esc(_('Specific month')); ?></option>
                    <option value="custom_range"<?php echo $filter['mode'] === 'custom_range' ? ' selected' : ''; ?>><?php echo $esc(_('Custom range')); ?></option>
                    <option value="days_back"<?php echo $filter['mode'] === 'days_back' ? ' selected' : ''; ?>><?php echo $esc(_('Days back')); ?></option>
                </select>
                <div class="veeamreport-field-hint"><?php echo $esc(_('Choose one mode. The matching month/date field below is then used.')); ?></div>
            </div>

            <div class="veeamreport-field" data-veeam-modes="specific_month">
                <label for="filter_month"><?php echo $esc(_('Month')); ?></label>
                <input id="filter_month" type="month" name="filter_month" value="<?php echo $esc($filter['month']); ?>">
            </div>

            <div class="veeamreport-field" data-veeam-modes="custom_range">
                <label for="filter_date_from"><?php echo $esc(_('Date from')); ?></label>
                <input id="filter_date_from" type="date" name="filter_date_from" value="<?php echo $esc($filter['date_from']); ?>">
            </div>

            <div class="veeamreport-field" data-veeam-modes="custom_range">
                <label for="filter_date_to"><?php echo $esc(_('Date to')); ?></label>
                <input id="filter_date_to" type="date" name="filter_date_to" value="<?php echo $esc($filter['date_to']); ?>">
            </div>

            <div class="veeamreport-field" data-veeam-modes="days_back">
                <label for="filter_days_back"><?php echo $esc(_('Days back')); ?></label>
                <input id="filter_days_back" type="number" min="1" max="366" name="filter_days_back" value="<?php echo $esc($filter['days_back']); ?>">
            </div>

            <div class="veeamreport-field">
                <label for="filter_source"><?php echo $esc(_('Data source')); ?></label>
                <select id="filter_source" name="filter_source">
                    <option value="auto"<?php echo $filter['source'] === 'auto' ? ' selected' : ''; ?>><?php echo $esc(_('Auto')); ?></option>
                    <option value="history"<?php echo $filter['source'] === 'history' ? ' selected' : ''; ?>><?php echo $esc(_('History')); ?></option>
                    <option value="trends"<?php echo $filter['source'] === 'trends' ? ' selected' : ''; ?>><?php echo $esc(_('Trends')); ?></option>
                </select>
                <div class="veeamreport-field-hint"><?php echo $esc(_('Auto switches to trends for periods longer than 7 days.')); ?></div>
            </div>

            <div class="veeamreport-field">
                <label for="filter_metric"><?php echo $esc(_('Metric')); ?></label>
                <select id="filter_metric" name="filter_metric">
                    <option value="size24h"<?php echo $filter['metric'] === 'size24h' ? ' selected' : ''; ?>><?php echo $esc(_('Backup size 24h')); ?></option>
                    <option value="size31d"<?php echo $filter['metric'] === 'size31d' ? ' selected' : ''; ?>><?php echo $esc(_('Rolling 31-day backup size')); ?></option>
                </select>
            </div>

            <div class="veeamreport-field">
                <label for="filter_top"><?php echo $esc(_('Top protected objects')); ?></label>
                <input id="filter_top" type="number" min="10" max="500" name="filter_top" value="<?php echo $esc($filter['top']); ?>">
            </div>

            <div class="veeamreport-field veeamreport-field--wide">
                <label for="filter_object_search"><?php echo $esc(_('Protected object search')); ?></label>
                <input id="filter_object_search" type="text" name="filter_object_search" value="<?php echo $esc($filter['object_search']); ?>" placeholder="<?php echo $esc(_('Name, platform, repository…')); ?>">
            </div>

            <div class="veeamreport-field veeamreport-field--wide">
                <label for="filter_repo_search"><?php echo $esc(_('Repository search')); ?></label>
                <input id="filter_repo_search" type="text" name="filter_repo_search" value="<?php echo $esc($filter['repo_search']); ?>" placeholder="<?php echo $esc(_('Repository or Veeam host…')); ?>">
            </div>

            <div class="veeamreport-field veeamreport-field--wide">
                <label for="filter_hostids"><?php echo $esc(_('Veeam hosts')); ?></label>
                <select id="filter_hostids" class="veeamreport-multiselect" name="filter_hostids[]" multiple>
                    <?php foreach (($report['host_options'] ?? []) as $host): ?>
                        <?php $selected = in_array((string) $host['hostid'], (array) $filter['hostids'], true); ?>
                        <option value="<?php echo $esc($host['hostid']); ?>"<?php echo $selected ? ' selected' : ''; ?>>
                            <?php echo $esc($host['name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <div class="veeamreport-field-hint"><?php echo $esc(_('Leave empty to include all available Veeam hosts.')); ?></div>
            </div>
        </div>

        <div class="veeamreport-form-actions">
            <button type="submit" class="veeamreport-btn-primary"><?php echo $esc(_('Apply')); ?></button>
        </div>
    </form>

    <script>
    (function(){
        var modeSelect = document.getElementById('filter_mode');
        if (!modeSelect) { return; }
        var fields = document.querySelectorAll('.veeamreport-filter-form [data-veeam-modes]');
        function applyMode(){
            var mode = modeSelect.value;
            for (var i = 0; i < fields.length; i++) {
                var modes = (fields[i].getAttribute('data-veeam-modes') || '').split(',');
                var visible = modes.indexOf(mode) !== -1;
                fields[i].classList.toggle('veeamreport-field--hidden', !visible);
            }
        }
        modeSelect.addEventListener('change', applyMode);
        applyMode();
    })();
    </script>

    <div class="veeamreport-downloads">
        <a class="btn-alt" href="<?php echo $esc($download_url('html')); ?>"><?php echo $esc(_('Download HTML')); ?></a>
        <a class="btn-alt" href="<?php echo $esc($download_url('daily_csv')); ?>"><?php echo $esc(_('Daily CSV')); ?></a>
        <a class="btn-alt" href="<?php echo $esc($download_url('hosts_csv')); ?>"><?php echo $esc(_('Hosts CSV')); ?></a>
        <a class="btn-alt" href="<?php echo $esc($download_url('repositories_csv')); ?>"><?php echo $esc(_('Repositories CSV')); ?></a>
        <a class="btn-alt" href="<?php echo $esc($download_url('objects_csv')); ?>"><?php echo $esc(_('Objects CSV')); ?></a>
    </div>

    <?php if (($report['summary']['cards'] ?? []) !== []): ?>
        <div class="veeamreport-summary-grid">
            <?php foreach ($report['summary']['cards'] as $card): ?>
                <div class="veeamreport-card">
                    <div class="veeamreport-card-label"><?php echo $esc($card['label']); ?></div>
                    <div class="veeamreport-card-value"><?php echo $esc($card['value']); ?></div>
                    <div class="veeamreport-card-sub"><?php echo $esc($card['sub']); ?></div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php include __DIR__.'/../partials/veeambackup.daily.table.php'; ?>
    <?php include __DIR__.'/../partials/veeambackup.hosts.table.php'; ?>
    <?php include __DIR__.'/../partials/veeambackup.repositories.table.php'; ?>
    <?php include __DIR__.'/../partials/veeambackup.objects.table.php'; ?>
</div>
<?php
$content = (string) ob_get_clean();

(new CHtmlPage())
    ->setTitle($data['title'])
    ->addItem(new CObject($content))
    ->show();
